### ISSUE TITLE
Registrator

### ISSUE THREAD

**Issue by fcdimitr** [nsailor/FastGraphletTransform.jl#3]
@nsailor 👋 

Please give permission to [Julia's automatic Registrator](https://github.com/JuliaRegistries/Registrator.jl) for this repository. Only the repository owner can do this. 

I will take care of releases afterwards.

**Comment by nsailor** [comment]
@JuliaRegistrator register branch=master

**Comment by nsailor** [comment]
@JuliaRegistrator register branch=master
